compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: /apdcephfs_cq10/share_1567347/share_info/nobelhu/code/llm_codebase/configs/8A100/ds_stage3.json
  zero3_init_flag: true
distributed_type: MULTI_GPU
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
gpu_ids: all
machine_rank: 0
main_process_ip: 11.220.86.19
main_process_port: 6000
main_training_function: main
megatron_lm_config: {}
mixed_precision: 'no'
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
use_cpu: false